### ISSUE TITLE
allow choosing transaction isolation level

### ISSUE THREAD

**Issue by fuchsnj** [sfackler/rust-postgres#115]
Right now `postgres::Connection.transaction` can only use the default transaction isolation level of `read commited`.
`repeatable read` and `serializable` may also be desired.
http://www.postgresql.org/docs/9.4/static/transaction-iso.html

**Comment by sfackler** [comment]
You can do this yourself by running `SET TRANSACTION ISOLATION LEVEL <whatever>`: http://www.postgresql.org/docs/9.4/static/sql-set-transaction.html. It probably makes sense to be able to specify a default isolation level that new transactions will be initialized with though.

**Comment by fuchsnj** [comment]
I was thinking it could get slightly better performance if you use something like
`START TRANSACTION ISOLATION LEVEL <whatever>` instead of 2 queries to start the transaction, then set the transaction level.

**Comment by sfackler** [comment]
Yep, that sounds pretty reasonable. I'll add a `Connection::set_transaction_isolation` (or whatever you want to call it) method tonight.

**Comment by fuchsnj** [comment]
sounds good

**Comment by sfackler** [comment]
So you can set the level globally by either setting the `default_transaction_isolation` parameter at initialization (e.g. `postgresql://postgres@localhost?default_transaction_isolation=serializable`) or by setting it at runtime using `SET SESSION CHARACTERISTICS AS TRANSACTION SERIALIZABLE`.

I'll add some methods to call into `SET SESSION ...` since it's a pretty obscure command (I didn't know it existed until I checked the implementation of the JDBC driver).

**Comment by sfackler** [comment]
Published in v0.8.7
