### ISSUE TITLE
Use Unicase or another case-insensitive comparison method for checking column names

### ISSUE THREAD

**Issue by reem** [sfackler/rust-postgres#136]
Postgres is case insensitive about column names but the impl of RowIndex for &str uses a case-sensitive comparison.

**Comment by sfackler** [comment]
Strictly speaking, it's only *sometimes* case insensitive - quoted identifiers are treated case-sensitively (i.e. if you have a table `foo`, `SELECT * from Foo` will work but `SELECT * from "Foo"` won't.

Do you know how the JDBC/Go/etc drivers handle this? I'm not strictly opposed to doing this, but I want to make sure case insensitive comparisons for this are common since if someone does something like this for some reason, things will break:
```
CREATE TABLE foo ();
CREATE TABLE "Foo" ();
```

**Comment by sfackler** [comment]
Looks like JDBC does lowercase column names: http://grepcode.com/file/repo1.maven.org/maven2/postgresql/postgresql/9.0-801.jdbc4/org/postgresql/jdbc2/AbstractJdbc2ResultSet.java#2577

**Comment by reem** [comment]
That would be fine to me, Unicase just avoids reallocating the lowercase string.

**Comment by sfackler** [comment]
This seems like a breaking-ish change, but I have some other pending breaking stuff so I'll probably roll it all out together in `0.10` sometime.
