### ISSUE TITLE
More flexible timezone configuration

### ISSUE THREAD

**Issue by barosl** [sfackler/rust-postgres#147]
rust-postgres currently sets `timezone` to `GMT` on startup. Recently, I was bitten by this behavior because I assumed it to be my local timezone. It seems that the GMT forcing is done to have an interoperability with the underlying `time` crate. So I wondered:
1. Would that be possible to remove that limitation? The official driver (libpq) doesn't have such a behavior, so it can be a bit confusing (to me, at least). However, I get that defaulting to GMT is [almost always a good idea](http://justatheory.com/computers/databases/postgresql/use-timestamptz.html), though.
2. Is it safe to `SET timezone to [local timezone]` manually? If the concern with the `time` crate still holds, it may break some assertions that the `Timespec` values are stored in GMT.

**Comment by sfackler** [comment]
`SET timezone TO whatever` should work fine as long as you aren't trying to send `time` or `chrono` types back and forth.

The right solution is for the `ToSql` and `FromSql` implementations to be able to translate properly based on the session's timezone. I haven't seen any Rust crates that deal with timezones, though, unfortunately.

**Comment by sfackler** [comment]
Oh yeah, one open question is: once tzdata support does make it in, what should the timezone be set to? The JDBC driver sets it to the local timezone, I believe, but we could also leave it as the default, or stick with GMT.

**Comment by ohmyarch** [comment]
@sfackler Is there any progress? I don't think such a default behavior is reasonable. Whenever a connection is established, I have to execute a statement to modify the time zone setting. This is really annoying.

**Comment by Jakubzik** [comment]
The local timezone seems to be the default setting of psql and JDBC, and would have been less surprising to me, too.

Also, I do not understand the effect of adding "options='-c timezone=Europe/Berlin'" to the connection configuration. There *is* an effect, because adding a non-existant timezone causes an error ("options='-c timezone=Curope/Berlin' results in a SqlState 22023 from postgres specifically complaining about the wrong timezone), but the timezone on the connection *remains* GMT even if I add the correct option for Berlin.
 
Would it be possible to make sure the option that is set in the configuration ("options=...") is transported to the connection?

**Comment by sfackler** [comment]
I was looking through the PostgreSQL source and realized that ever since switching from the text format to the binary format, we haven't actually needed to set the time zone to UTC - the server just always uses UTC for the values of timestamp-aware types. Be aware that the `TimeZone` session parameter has no effect on values transmitted via ToSql and FromSql, but we should be able to stop explicitly forcing it to UTC.
