### ISSUE TITLE
Why are ToSql and FromSql different traits?

### ISSUE THREAD

**Issue by jeff-davis** [sfackler/rust-postgres#21]
First of all, please tell me if there is a better forum for discussion like this. Also, as a disclaimer, I am very new to rust.

A type is pretty useless unless it has conversions in both directions, right? So why not just make one trait for both directions?

Also, what is the model for binary versus text representations? Going in, it seems like the type can represent itself as either text or binary; but coming back, the type needs to either support both, or at least declare which one it does support.

**Comment by zoombinis** [comment]
@sfackler I'm new so forgive me if I've missed docs somewhere, but how do you specify in `.query` that you are inserting a value of type `INT4RANGE`?

Through the one documented example I've seen, I understand how int and string values work, but it's not obvious to me what more is needed for more complex types.

Thanks and I'm responding here since you mentioned implementing `INT4RANGE` above.
