### ISSUE TITLE
Feature Request: Optionally disable use of the log crate

### ISSUE THREAD

**Issue by pdtilton** [sfackler/rust-postgres#215]
I am interested in using postgres as a logging backend in conjunction with the log crate.  The issue is that anytime such a logger creates a query it results in infinite recursion due to the use of the `debug!` and `info!` log macros in src/lib.rs.  Would it be possible to optionally disable this feature in rust-postgres? I'm fairly new to Rust, so perhaps there is a workaround I am not considering instead.

**Comment by sfackler** [comment]
Haha, that's something I haven't thought of! Seems like a reasonable way to fix this would be to add a feature to disable logging.

**Comment by pdtilton** [comment]
Wow!  That was fast.  I was just looking into approaches to tackle the issue.  Thank you very much, sir!

**Comment by stevenliebregt** [comment]
It seems this no longer exists in the current version, is it possible to bring this back?

**Comment by sfackler** [comment]
I think a pluggable trait would be the preferred way to go here, like what's discussed in #1053.

**Comment by stevenliebregt** [comment]
Is there any progress in that PR, or could I propose a quick feature based solution in the meantime? I'm using this crate in an FFI context with Node, and with large queries it keeps crashing the processes because rust expects stdout to be blocking, and node doesn't. Simply setting the node stdout to blocking isn't a great solution as it might block the node event loop as well.

**Comment by sfackler** [comment]
You could not log to stdout when running in an FFI context with Node.
