### ISSUE TITLE
Request for feature: support geometric types with rust-geo

### ISSUE THREAD

**Issue by kestred** [sfackler/rust-postgres#244]
Would it make sense to support postgreSQL's builtin geometric types using the https://github.com/georust/rust-geo crate?

It is the most used (and i.m.o. seems the most well designed) crate that exists for geo/gis in rust. 

## Type Correspondence

<table>
    <thead>
        <tr>
            <th>Rust Type</th>
            <th>Postgres Type</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>geo::Coordinate, geo::Point</td>
            <td>POINT</td>
        </tr>
        <tr>
            <td>(possibly geo::LineString or geo::MultiPoint)</td>
            <td>LINE, LSEG</td>
        </tr>
        <tr>
            <td>geo::Bbox</td>
            <td>BOX</td>
        </tr>
        <tr>
            <td>geo::LineString</td>
            <td>PATH</td>
        </tr>
        <tr>
            <td>geo::Polygon</td>
            <td>POLYGON</td>
        </tr>
    </tbody>
</table>

**Comment by sfackler** [comment]
Sure, sounds reasonable to me! I'd be happy to take PR adding the conversions, or I can take a crack at it when I have a chance.

**Comment by kestred** [comment]
Great.  I'll implement it and create a PR.

**Comment by pka** [comment]
This could lead to some confusion. People working with geometries within PostgreSQL are using PostGIS. https://github.com/andelf/rust-postgis isn't using rust-geo geometries, because it leads to overhead for converting between different geometry implementations. There was a long [discussion](https://github.com/georust/rust-geo/issues/67) about that, which ended in the consensus that rust-geo needs a trait based implementation.

**Comment by rofrol** [comment]
Close issue?
