### ISSUE TITLE
postgres-protocol v0.3.1 was a breaking change and should be yanked

### ISSUE THREAD

**Issue by golddranks** [sfackler/rust-postgres#290]
`postgres-protocol v0.3.1` includes a bump from `generic-array v0.7` to `generic-array v0.8`. I don't know why, but having different major versions of generic-array in the same build generally breaks it, even if it isn't exposed in the public API. Therefore the 0.3.1 bump was a breaking change for anybody that is using a crate that depends on `generic-array v0.7`.

Btw. I've seen breakage with generic-array before, and I'd greatly appreciate if somebody helped me understand *why* it induces breaking changes.

0.3.1 should be yanked, and 0.4 released instead.

**Comment by sfackler** [comment]
generic-array 0.7 depended on typenum `~1.5` rather than the more normal `1.5` (i.e. `^1.5`). This means it claims it can't work with typenum 1.7 even though they are semver compatible. generic-array 0.8 now has a fixed version constraint but 0.7 doesn't.

@fizyk20 can you make one final 0.7 release to fix things up when depending on both versions?

**Comment by sfackler** [comment]
A fixed version of generic-array 0.7 has been published so this should be resolved - please reopen if not!
