### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by fschutt** [sfackler/rust-postgres#305]
The error management in `postgres` is currently worse than the `0.14` one.

For example, the `connect()` function returns a generalized error. Why can't it return a `DbError` or a `ConnectError` like the 0.14 API? How am I supposed to wrap this - put everything in the `postgres::Error` module? So I would have to account for my database connection maybe returning an SQL error, which can never happen. How should I efficiently match on the errors - compare them with constants? Rust is supposed to migrate away from the error-code like matching ... but the `0.15` API is bringing it back with error codes and constants ... that's what enum variants are for. Why does every method return a full `postgres::Error` - in `0.14` you had `ConnectError` and `SqlState`-error as enums, so you could match against their variants. The `0.15` API just lumps them together and you have to use `unwrap()` to get to the inner error and check their error code with some hard-coded constant. Why are these not simply variants? Why?

The `SqlState` error also doesn't implement `std::error::Error` - so it can't be wrapped in `error_chain`, which is great.

**Comment by sfackler** [comment]
> Why can't it return a DbError

`connect` can't return a `DbError` because many of the failure modes are not the database returning an error to you.

> or a ConnectError

What would this look like? How would it be different from `Error`?

> How am I supposed to wrap this - put everything in the postgres::Error module?

Put what in the `postgres::error` module exactly?

> So I would have to account for my database connection maybe returning an SQL error, which can never happen.

That can, in fact, happen. Authentication failures are returned as SQL errors, for example. That's why there was a [`ConnectError::Db`](https://docs.rs/postgres/0.14.2/postgres/error/enum.ConnectError.html) variant in 0.14!

> How should I efficiently match on the errors - compare them with constants?

Yep. They are helpfully defined for you in the `error` module.

> Rust is supposed to migrate away from the error-code like matching

It's "supposed to"?

> The 0.15 API just lumps them together and you have to use unwrap() to get to the inner error and check their error code with some hard-coded constant.

What is the difference between matching against [`INVALID_AUTHORIZATION_SPECIFICATION`](https://docs.rs/postgres/0.15.1/postgres/error/constant.INVALID_AUTHORIZATION_SPECIFICATION.html) and [`SqlState::InvalidAuthorizationSpecification`](https://docs.rs/postgres/0.14.2/postgres/error/enum.SqlState.html)?

> Why are these not simply variants?

New SQLSTATE codes are added over time, and it's a breaking change to add new variants to [`SqlState`](https://docs.rs/postgres/0.14.2/postgres/error/enum.SqlState.html). Similarly, new types are added over time and it's a breaking change to add them to [`Type`](https://docs.rs/postgres/0.14.2/postgres/types/enum.Type.html).

> API just lumps them together and you have to use unwrap() to get to the inner error

There shouldn't be any unwrapping required. See for example [this bit of code](https://github.com/sfackler/rust-postgres/blob/master/postgres/src/lib.rs#L854).

> The SqlState error also doesn't implement std::error::Error

It has never implemented `Error`, and I don't really understand why it would? What's the rationale for wanting to throw away all of the extra information about the error and only propagate the error code?

**Comment by fschutt** [comment]
I am sorry, I misunderstood the error management. Please excuse my rude tone. I was used to using one `Connection` error and a different error for everything else (like actual queries). I did not know that Authentication errors are done via SQL. So I was used to have (as an `error-chain` wrapper) seperate errors for connecting and everything else. 

Are all error codes simply directly wrapped from Postgres? So that I could filter out what actual connection errors are via using the `Class 08 — Connection Exception` - errors in postgres? Or are there other error codes possibly returned from the `connect()` function?

**Comment by sfackler** [comment]
`SqlState` error codes are only produced when the database returns an error message. Other errors that can occur when connecting are `io::Errror`s if there's a socket-level problem, or an error from the TLS implementation if there's an error handshaking, or an error from this crate if the database requested a password and there wasn't one provided.
