### ISSUE TITLE
`#` character in password causes failure with "Non-digit characters in port."

### ISSUE THREAD

**Issue by pka** [sfackler/rust-postgres#306]
When passing a connection URI like `postgresql://user:pwd#1@localhost/db` I get `Non-digit characters in port.`

BTW, is there a recommendation for passing the password in a secure way?

**Comment by sfackler** [comment]
Reserved characters (including #) in the password portion of a URL need to be percent encoded.

What do you mean by a secure way?

**Comment by pka** [comment]
Which characters are reserved?

Storing a connection URI with a clear-text password in a configuration file or passing it in a shell is potentially insecure. libpq supports storing passwords in `.pgpass` or passing via `PGPASSWORD`.

**Comment by sfackler** [comment]
https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

I'm assuming you're trying to protect against other users on the same machine from reading the password out of the configuration file? (`PGPASSWORD` is explicitly discouraged because other users can examine environment variables in some systems: https://www.postgresql.org/docs/10/static/libpq-envars.html). You can always drop the permissions of the config file down to 600, or do whatever else and assemble `ConnectParams` explicitly.

**Comment by pka** [comment]
Permission 600 for .pgpass is enforced by libpq. Setting the same for an application configuration file can be difficult to enforce and prevents adding it to a version control system.
Passing secrets by environment variables is very common, e.g. in CI services.

**Comment by sfackler** [comment]
Checking secrets into a git repository is a slightly scary world to be in, but it happens from time to time for sure.

To specifically answer your question, there aren't any formal recommendations on how to manage secrets for rust-postgres in particular. IME it's typicaly integrated with the secret management for the application as a whole.
