### ISSUE TITLE
What the reason why tokio_postgres::Client is not deriveing Clone?

### ISSUE THREAD

**Issue by andreytkachenko** [sfackler/rust-postgres#380]
Is any specific reason why it not deriveing `Clone`?:

```rust
pub struct Client(proto::Client);
```

Note: `proto::Client` is clonable;

**Comment by sfackler** [comment]
Connections are stateful, so it seems a bit dangerous to have multiple handles to the same one.

**Comment by andreytkachenko** [comment]
To be on the same page, under `Connection` you meant `Client` struct right?
```rust
pub struct Client(proto::Client);
```
and `proto::Client`:
```rust
struct Inner {
    state: Mutex<State>,
    sender: mpsc::UnboundedSender<Request>,
}

#[derive(Clone)]
pub struct Client(Arc<Inner>);
```
not the `Connection` struct:
```rust
pub struct Connection {
    stream: Framed<Box<TlsStream>, PostgresCodec>,
    cancel_data: CancelData,
    parameters: HashMap<String, String>,
    receiver: mpsc::UnboundedReceiver<Request>,
    pending_request: Option<RequestMessages>,
    pending_response: Option<Message>,
    responses: VecDeque<mpsc::Sender<Message>>,
    state: State,
}
```
???

**Comment by sfackler** [comment]
I meant the "idea" of a connection to a postgres database, not the specific `Connection` type, yes.

**Comment by coder543** [comment]
Without `#[derive(Clone)]` on `Client`, I have been unable to prove that it is possible to build and execute a meaningful transaction.

The only two tests that I could find for Transaction currently prepare and execute a single query each. I'm not sure what the use cases are for transactions that only execute one query.

In my case, I need to be able to execute a chain of queries based on previous results.

1. Transaction begins
2. Query A selects from Table 1.
3. Query B selects from Table 2.
4. Queries C...F insert/update/delete into Tables 1, 2, and 3 based on the results from A and B.
5. Transaction is committed (assuming no previous errors)

I need all of these queries to be run inside a single transaction so that if any of them fail, or if the connection fails, or whatever else could happen, it maintains transactional guarantees.

As it is, it is not possible to have a chain of queries, since subsequent queries would be constructed inside an `and_then` (or similar) closure, and require that the Client be `move`d into the closure. Once that happens, it is no longer possible to wrap the outer query future in a transaction. It is not possible to share references to the Client, because mutable access is required for... everything.

By forking this library and adding the `#[derive(Clone)]`, I was able to make everything work just fine.

Are there any dangers with this approach that you're aware of? If not, I would be really excited for this `#[derive(Clone)]` to be added to this repo. Otherwise, I don't see how this Transaction API can be used in a real world application, and I would love to see a good example of a sequence of queries that are dependent on previous results.

The primary danger I can see is if someone tried to start a transaction while a transaction was already open. It should be possible to return an error if Postgres warns that there is already a transaction in progress, and this error would be deterministic every time a nested transaction is started. It should be a reasonable trade-off between what can be encoded in the type system and the large, shared, concurrently mutable state that Postgres is.

**Comment by sfackler** [comment]
Yeah, the current transaction method is bad for not just this reason, but I don't think that making `Client` clonable is the right solution.

**Comment by DarrenTsung** [comment]
A different approach:

Add a `transaction_builder()` method which returns a `TransactionBuilder` which has the cloned `Client` internally. 

Then users who are converting postgres futures into a transaction can just create this TransactionBuilder before creating their Future (which takes ownership of the `Client`) and call `builder.build(future)` to get the `Transaction`.

This avoids changing the API drastically and also supports sequential executions with a connection using a transaction.

Do you think this would be a better solution @sfackler?

**Comment by sfackler** [comment]
I think that could work, definitely. Interested in writing it up in a PR?

**Comment by sfackler** [comment]
#384 should resolve this.

**Comment by sfackler** [comment]
> Why else would Client be an Arc (with one indirection)?

The interior is reference counted as an internal implementation detail.

> Not being Clone _and_ requiring `&mut self` (both arguably unnecessarily) is just painful in many cases.

It is designed to prevent bugs. Connections are stateful objects that shouldn't be used concurrently by multiple independent tasks. Otherwise state changes (like transaction boundaries) will be interleaved which is not what you want to have happen.

> If Client keeps requiring `&mut self`, the above code would require a Mutex, killing performance.

What are the specific numbers of the performance killing Mutex that you've found through your careful benchmarking of the code?

**Comment by kosta** [comment]
> Connections are stateful objects that shouldn't be used concurrently by multiple independent tasks. Otherwise state changes (like transaction boundaries) will be interleaved which is not what you want to have happen.

That is a good point! I need to understand the interaction of pipelining and transactions more before I can continue this conversation.

**Comment by sfackler** [comment]
TransactionBuilder is a problem, yes. I'm not sure what the right approach there is.

**Comment by kosta** [comment]
Hm, would it be feasible for a transaction to "block" further pipelining until it is commited/rolled back? 

E.g. this would not really block: "BEGIN; UPDATE accounts SET amount = amount + 10 WHERE id = 5; UPDATE accounts SET amount = amount - 10 WHERE id = 6; COMMIT".

But this would block everything else in the pipeline: "BEGIN; SELECT amount FROM accounts where id = 5;", send http request to cloud service to increment amount by 10, "UPDATE accounts SET amount = ? where id = 5; COMMIT;"

Of course this would have a performance impact as it basically shuts down pipelining in some cases. But it's better than interleaving transactions.

**Comment by sfackler** [comment]
That is one possibility, though I'd ideally like prefer to avoid making transactions special in the implementation. It might be the only foolproof option though.

**Comment by kosta** [comment]
If you want to support "Idle transactions" (i.e. do some non-sql stuff with an intermediate transaction result), it seems you might need to make a special case for it :)

What are the alternatives?

* Push the problem to the user. Idea: Use an "async RWLock" that acquires write locks for "idle transactions" and read locks for other queries. With the right semantic, this should not introduce deadlocks.

(Cant really think of anything else at the moment other than "not solve it")

**Comment by kosta** [comment]
I will try to prototype the "foolproof idle transcations" approach. I think I have an idea on how to do this in a nice way with mimimal code changes, let see how this blows up in my face ;)
