### ISSUE TITLE
Add Client::poll_idle

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-postgres#403]
It would return Ready when there are no outstanding requests. This would include both requests that are actively queued or being processed as well as those that have been created as futures but not yet polled.

This could be used by connection pools to avoid returning a connection to a pool until its associated requests have actually completed. You can otherwise run into awkward situations where one checkout's requests begin interleaving with another's.

cc @jwilm

**Comment by jbg** [comment]
This function seems to have disappeared in the latest alpha. We were using it internally for our database connection pool – are there plans to bring it back, or is there an alternative way to achieve the same result (waiting for a client to become idle that the pool has been given back due to its wrapper being dropped) that you’d suggest?

**Comment by sfackler** [comment]
Futures now borrow the client, so once you have the client back by-value you know already that it's idle.

**Comment by jbg** [comment]
Makes sense, thanks!
