### ISSUE TITLE
tokio_postgres: simplify Client::execute and Client::query

### ISSUE THREAD

**Issue by s-panferov** [sfackler/rust-postgres#432]
Hello @sfackler, I'm playing with the library and so far two issues are very annoying:

1. Having to use `Arc<RwLock<Client>>` is painful. But this was previously reported, and I don't know if this can be fixed easily.
2. Having to `prepare` statements even for one-shot queries. Can we make this more ergonomic by introducing some kind of a Trait abstraction to allow `&str` inputs?

**Comment by sfackler** [comment]
> 1. Having to use `Arc<RwLock<Client>>` is painful. But this was previously reported, and I don't know if this can be fixed easily.

I'd recommend using a connection pool like https://crates.io/crates/bb8

> 2\. Having to `prepare` statements even for one-shot queries. Can we make this more ergonomic by introducing some kind of a Trait abstraction to allow `&str` inputs?

I want to, but not currently, unfortunately. Specifically, we can't encode query parameters until after the statements is prepared, but they're borrowed. Once async-await lands we'll be do this since our Query future won't have to be `'static` anymore.

**Comment by s-panferov** [comment]
@sfackler thanks!

**Comment by s-panferov** [comment]
@sfackler I've tried bb8, but it's a hell. Having to pass client by value through all the results and errors create a ton of boilerplate because you have to use `.then` chaining. I hope we can do better, for not it's nearly unusable.
