### ISSUE TITLE
tokio_postgres::NoTls doesn't impl Clone.

### ISSUE THREAD

**Issue by fakeshadow** [sfackler/rust-postgres#495]
It used to impl Clone in `tokio-postgres-0.4.0-rc.3` and it's useful for generic connection management with dynamic tls input.

**Comment by dutchmartin** [comment]
I see no reason why you can not create a new instance of it, since it seems that NoTls [is a zero sized struct](https://github.com/sfackler/rust-postgres/blob/c92e95dac2403a58dc105e56b05022d35cb5e122/tokio-postgres/src/tls.rs#L74).
Can you please explain in more detail what you are trying to achieve?

**Comment by fakeshadow** [comment]
I'm setting up a generic connection pool and may or may not pass NoTls to it so that I can clone the tls and config to spawn new connections. But I can't make a trait bound with Clone when NoTls is not.
Sure I can go around it like pass Option<M: MakeTlsConnection> to it and construct a NoTls when it's None but I think it make more sense when a single line of derive macro can fix the problem.

I don't know why it's removed in master branch so I'm just assuming it would affect the code base. Please let me know if it's not as simple as I thought.

**Comment by fakeshadow** [comment]
Thanks very much for the quick help.
