### ISSUE TITLE
Implement more authentication methods

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-postgres#5]
Right now we support trust, password and md5. Of the remaining methods, KerberosV5 is deprecated and probably not worth supporting and SCMCredential doesn't apply since we don't use Unix domain sockets. That leaves GSS and SSPI.

**Comment by LukaszDargiewicz** [comment]
SSPI is commonly used in enterprise. I was happy when @pgjdbc had added support for SSPI authentication via waffle library about 2 years ago and since then I used this method in my java project. 
Now that I become Rust fan, I am looking for SSPI support in rust-postgres.
Until now i found SSPI support in winapi crate as a good start point.

**Comment by mhseiden** [comment]
It looks like https://www.postgresql.org/docs/current/static/auth-methods.html#AUTH-CERT is missing from your list of currently supported and yet to be supported auth methods. Any thoughts on supporting it?

**Comment by sfackler** [comment]
I think that should already be supported - you'd just need to configure your TLS implementation to send the client cert.
