### ISSUE TITLE
Tokio-postgres stops tasks from spawning when using tokio Basic Scheduler

### ISSUE THREAD

**Issue by nate-onesignal** [sfackler/rust-postgres#522]
The tokio basic scheduler runs all tasks on one thread. It is generally used in tests so that a panic on one future is propagated up to the the main thread of the test and the test runner can catch and display it as a failed test. When using tokio-postgres with the basic scheduler, calls to `tokio::spawn` will silently fail after calling `tokio_postgres::connect`. Here is a small example program:

```
#[tokio::main(basic_scheduler)]
async fn main() {
    tokio::spawn(async { dbg!() });

    let _ = tokio_postgres::connect(
        "postgres://pass_user:password@localhost:5433/postgres",
        tokio_postgres::NoTls,
    )
    .await
    .unwrap();

    tokio::spawn(async { dbg!() });
}
```

And the dependencies are:

```
[dependencies]
tokio = { version ="0.2", features = ["full"]}
tokio-postgres = "0.5.0-alpha.2"
```

Running this program, I expect the output to be:

```
[src/main.rs:3]
[src/main.rs:12]
```

And when running with the multithreaded scheduler, this is what you get. But with the basic scheduler, the output is only

```
[src/main.rs:3]
```

I'm not sure what tokio-postgres is doing that seems to be messing with the basic scheduler, but it should at least be documented that this library is incompatible with it or, ideally, made to work with it.

**Comment by sfackler** [comment]
This does not have anything to do with the tokio-postgres library.

`#[tokio::main]` only waits for the main future to complete before returning. It does not wait for all spawned futures. When using the multi-threaded runtime, it happens to be the case that the spawned dbg future runs before the program exits (it might not on a system with 1 core for example, though). On the basic scheduler, it will never run since the program will exit immediately after the spawn finishes without ever polling it.

**Comment by nate-onesignal** [comment]
Sorry, my real issue was using a thread-blocking mutex instead of an async one, but my bug tracking led me to think it was tokio-postgres.
