### ISSUE TITLE
Question about (client, connection) split

### ISSUE THREAD

**Issue by jeff-davis** [sfackler/rust-postgres#704]
The docs here ( https://docs.rs/tokio-postgres/0.6.0/tokio_postgres/ ) say:

"The connection object performs the actual communication with the database, so spawn it off to run on its own."

But I don't fully understand why this is necessary. Can you explain why there can't just be one object (either called "client" or "connection") for which all operations are async? Why does the caller need to care where the async operations are run, isn't that the job of the runtime?

**Comment by sfackler** [comment]
The caller needs to care where the async operations are run because we don't assume that a particular runtime is in use, so we can't automatically spawn off the connection to run in the background.

The client/connection split approach was borrowed from `hyper`. The `Client` could store the stream internally and not require a `Connection`, but there are a few advantages to the current approach:

1. It means that asynchronous notices and notifications are always being processed, even when the client itself is not in use.
2. It would be *significantly* more complex to implement query pipelining if `Client` handled the IO.
3. The `Connection<S, T>` can have the type parameters for the IO stream while `Client`'s type name stays nice and short.

**Comment by jeff-davis** [comment]
Thank you for the explanation.
