### ISSUE TITLE
How to move to the next result set? 

### ISSUE THREAD

**Issue by kingluo** [sfackler/rust-postgres#763]
One query may be multiple query statements, so it would contain multiple result sets.
How to move to the next result set?

**Comment by sfackler** [comment]
Prepared statements cannot contain multiple queries.

**Comment by kingluo** [comment]
Yes, I know, but for simple query, how to move to next result set?

**Comment by sfackler** [comment]
Simple query returns a stream of `SimpleQueryMessage`s, and the `CommandComplete` variant indicates the end of each result set: https://docs.rs/postgres/0.19.1/postgres/enum.SimpleQueryMessage.html

**Comment by kingluo** [comment]
Is there a streaming way to retrieve the messages? I check the code and found `simple_query_raw` is public only in the crate level.

**Comment by kingluo** [comment]
Side question, does tokio-postgres read packets from the network on demand?

**Comment by sfackler** [comment]
I can't remember why simple_query returns a Vec rather than a stream - it probably makes sense to expose simple_query_raw and probably change the interface over to that in the next breaking release.

There is a limited amount of buffering internally, so it will read from the network only when there's space.
