### ISSUE TITLE
`"__r#type"` is not a valid identifier

### ISSUE THREAD

**Issue by ShadowJonathan** [sfackler/rust-postgres#839]
I currently have to work with the raw identifier `r#type`, as one database table is using this. I can't change this name, as i'm merely reading out the data from a pre-existing format.

However, when i try to put in a struct format, like so;

```rs
#[derive(Debug, ToSql, FromSql)]
struct DeviceInboxMessageFormat {
    pub messages: Json<HashMap<UserId, HashMap<DeviceId, Value>>>,
    pub sender: UserId,
    pub r#type: String,
}
```

The proc-macro panics on;

```
error: proc-macro derive panicked
  --> adapters/synapse/src/extract.rs:83:24
   |
83 | #[derive(Debug, ToSql, FromSql)]
   |                        ^^^^^^^
   |
   = help: message: `"__r#type"` is not a valid identifier
```

I think this problem will be the same across all raw identifiers.

**Comment by sfackler** [comment]
It looks like it's due to this line: https://github.com/sfackler/rust-postgres/blob/master/postgres-derive/src/fromsql.rs#L122, which is actually mirroring an example in proc-macro2: https://docs.rs/proc-macro2/1.0.32/proc_macro2/struct.Ident.html#examples.

It may be a bug in either proc-macro2 or the stdlib proc-macro?

**Comment by ShadowJonathan** [comment]
https://github.com/dtolnay/proc-macro2/issues/234

**Comment by sfackler** [comment]
https://github.com/dtolnay/proc-macro2/issues/302
