### ISSUE TITLE
Issue when running .query() against pgbouncer

### ISSUE THREAD

**Issue by sbdchd** [sfackler/rust-postgres#959]
I recently switched to using pgbouncer in front of postgres instead of querying it directly and ran into the following error:

```
db error: ERROR: prepared statement "s3817" already exists%                                  
```

asyncpg shows the following error when trying to use an a prepared statement with pgbouncer set to `transaction`:

```
asyncpg.exceptions.InvalidSQLStatementNameError: prepared statement "__asyncpg_stmt_35__" does not exist
HINT:  
NOTE: pgbouncer with pool_mode set to "transaction" or
"statement" does not support prepared statements properly.
You have two options:

* if you are using pgbouncer for connection pooling to a
  single server, switch to the connection pool functionality
  provided by asyncpg, it is a much better option for this
  purpose;

* if you have no option of avoiding the use of pgbouncer,
  then you can set statement_cache_size to 0 when creating
  the asyncpg connection object.
```

**Comment by sfackler** [comment]
Like the error message says, pgbouncer doesn't handle prepared statements properly. You'd either need to reconfigure pgbouncer so they do work or only use the batch_execute and query_raw methods which do not use prepared statements.

**Comment by sbdchd** [comment]
thank you for the quick response!

I switched over from `.query` to `.query_raw` and still see errors about prepared statements

I'm using bb8 for a connection pool, not sure if that's related

**Comment by veerapatyok** [comment]
I have a same problem too when set `pgbouncer` to `transaction` mode, quick fix(luckily I don't have param ) I use `simple_query` but when I want to use `param` I dont see any method support this problem

**Comment by helios2k6** [comment]
I'm also running into this issue. Not sure why this issue has been closed, as there is no solution that requires:

(1) The ability to substitute parameters (e.g. an HStore parameter) into a SQL string and 
(2) Executing without using a prepared statement

Several other known libraries in other languages provide both facilities (e.g. Java's PG Data Source with its prepareThreshold = 0), and pg_bouncer is widely used in the industry. Clearly, this crate can, and should, be improved.

Closing this issue is the incorrect solution, and so is asking clients to use the `query_raw` or `simple_query` methods as that requires clients to parse and format their query strings manually.

I propose the writers of this crate reopen this issue and track an enhancement to allow, at least, client-side formatting of SQL strings with parameters.
